apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog-deployment
  labels:
    app: book-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers:
        - name: book-catalog
          image: projectpart5.azurecr.io/book_catalog:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          workingDir: /usr/src/app/book_catalog
          command: ["uvicorn"]
          args: ["app.main:app", "--host", "0.0.0.0", "--port", "5000"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management-deployment
  labels:
    app: inventory-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers:
        - name: inventory-management
          image: projectpart5.azurecr.io/inventory_management:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          workingDir: /usr/src/app/inventory_management
          command: ["uvicorn"]
          args: ["app.main:app", "--host", "0.0.0.0", "--port", "5000"]
---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog-service
spec:
  selector:
    app: book-catalog
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-management-service
spec:
  selector:
    app: inventory-management
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
