name: "Terraform Deployment"

on:
  push:
    branches:
      - main
    paths:
      - "terraform_scripts/**"
  pull_request:
    branches:
      - main
    paths:
      - "terraform_scripts/**"
  workflow_dispatch:

# Special permissions required for OIDC authentication
permissions:
  id-token: write
  contents: read

# Environment variables for Azure authentication using OIDC
env:
  ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
  ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
  ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"

jobs:
  setup-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.6"

      - name: Authenticate to Azure using OIDC
        id: auth
        uses: azure/github-actions-oidc-provider@v1

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ env.ARM_CLIENT_ID }}
          tenant-id: ${{ env.ARM_TENANT_ID }}
          subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}
          allow-no-subscriptions: true
          federated-token: ${{ steps.auth.outputs.oidc-token }}

      - name: Terraform Initialize
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
