name: "Terraform Deployment"

on:
  push:
    branches:
      - main
    paths:
      - "terraform_scripts/**"
  pull_request:
    branches:
      - main
    paths:
      - "terraform_scripts/**"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  setup-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.6"

      - name: Azure Login via OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Change to Terraform Scripts Directory
        run: cd terraform_scripts

      - name: Terraform Initialize
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
